sudo: false
dist: trusty
language: ruby

before_install:
  - gem install bundler -v 1.15.2

rvm:
  - "2.4"
  - "2.3"
  - "ruby-head"
  - "rbx-3"
  - "jruby"
  - "jruby-head"

gemfile:
  - "gemfiles/Rack-1.gemfile"
  - "gemfiles/Rack-2.gemfile"

matrix:
  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
